services:
  noray:
    image: ghcr.io/foxssake/noray:main
    container_name: noray
    restart: unless-stopped
    ports:
      - "8890:8890"                 # TCP signalling
      - "8891:8891"                 # HTTP metrics (optional)
      - "8809:8809/udp"             # UDP registrar
      - "50001-50100:50001-50100/udp"   # Relay UDP range
    environment:
      NORAY_OID_LENGTH: 21
      NORAY_OID_CHARSET: "useandom-26T198340PX75pxJACKVERYMINDBUSHWOLF_GQZbfghjklqvwyzrict"
      NORAY_PID_LENGTH: 128
      NORAY_PID_CHARSET: "useandom-26T198340PX75pxJACKVERYMINDBUSHWOLF_GQZbfghjklqvwyzrict"
      NORAY_SOCKET_HOST: "0.0.0.0"
      NORAY_SOCKET_PORT: 8890
      NORAY_HTTP_HOST: "0.0.0.0"
      NORAY_HTTP_PORT: 8891
      NORAY_UDP_RELAY_PORTS: "50001-50100"
      NORAY_UDP_RELAY_TIMEOUT: "30s"
      NORAY_UDP_RELAY_CLEANUP_INTERVAL: "30s"
      NORAY_UDP_REGISTRAR_PORT: 8809
      PUBLIC_ADDR: "192.168.0.111"   # CHANGE THIS, Example "181.181.181.181" or "https://cat.com"
      NORAY_LOGLEVEL: "info"
    networks:
      - matchlay-net

  matchmaker:
    build:
      context: https://gittea.destinyend.com/Edge_lord/MatchLay.git
    container_name: matchmaker
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=                # CHANGE THIS, Example "D3Fbw2*32f2a1fdsw"
      - PUBLIC_ADDR=192.168.0.111  # CHANGE THIS, Example "181.181.181.181" or "https://cat.com"
      - HTTP_PORT=8000
      - NORAY_HOST=noray          
      - NORAY_PORT=8890
    networks:
      - matchlay-net
    depends_on:
      - noray
    healthcheck:
    test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
    interval: 30s
    timeout: 5s
    retries: 3

networks:
  matchlay-net:
    driver: bridge
